import type { TopicExperience } from '@/schemas/topic-experience';

// Routing and presentation pointers only. Clinical wording lives in the audited blocks.
export const experience = {
  pages: [
    {
      slug: 'assessment',
      title: 'Assessment',
      shortTitle: 'Assess',
      quickJump: true,
      description: 'Presentation, examination and important alternatives.',
      group: 'Clinical',
      sectionIds: ['presentation', 'assessment', 'differential-diagnoses'],
      aliases: ['presentation', 'history', 'examination'],
      keywords: ['pain', 'deterioration', 'differentials'],
    },
    {
      slug: 'investigations',
      title: 'Investigations',
      shortTitle: 'Investigate',
      quickJump: true,
      description: 'Tests, imaging and the diagnosis in context.',
      group: 'Clinical',
      sectionIds: ['investigations', 'imaging', 'diagnosis-and-severity'],
      aliases: ['imaging', 'diagnosis'],
      keywords: ['bloods', 'urine', 'ultrasound', 'CT', 'MRI', 'severity'],
    },
    {
      slug: 'management',
      title: 'Management',
      shortTitle: 'Manage',
      quickJump: true,
      description: 'Initial care, treatment options and special situations.',
      group: 'Clinical',
      sectionIds: ['management', 'special-situations'],
      aliases: ['treatment'],
      keywords: ['antibiotics', 'source control', 'abscess'],
    },
    {
      slug: 'anatomy',
      title: 'Anatomy',
      quickJump: true,
      description: 'Structures, relationships and operative relevance.',
      group: 'Operative',
      sectionIds: ['surgical-anatomy'],
      aliases: ['surgical anatomy'],
      keywords: ['caecum', 'mesoappendix', 'taeniae'],
    },
    {
      slug: 'appendicectomy',
      title: 'Appendicectomy',
      shortTitle: 'Operate',
      quickJump: true,
      description: 'Preparation, sequence and operative judgement.',
      group: 'Operative',
      sectionIds: ['laparoscopic-appendicectomy'],
      aliases: ['laparoscopic appendicectomy', 'appendectomy'],
      keywords: ['positioning', 'ports', 'base', 'retrieval'],
    },
    {
      slug: 'post-op',
      title: 'Post-op',
      description: 'Review, recovery, discharge and follow-up.',
      group: 'Operative',
      sectionIds: ['postoperative-care'],
      aliases: ['postoperative care'],
      keywords: ['recovery', 'discharge', 'histology'],
    },
    {
      slug: 'complications',
      title: 'Complications',
      quickJump: true,
      description:
        'Patient-information context and supported response principles.',
      group: 'Operative',
      sectionIds: ['complications'],
      aliases: ['postoperative concerns'],
      keywords: ['infection', 'bleeding', 'ileus', 'VTE'],
    },
    {
      slug: 'consent',
      title: 'Consent',
      description: 'Support an individual decision, beyond a checklist.',
      group: 'Operative',
      sectionIds: ['consent'],
      aliases: ['supported decision-making'],
      keywords: ['alternatives', 'material risks', 'understanding'],
    },
    {
      slug: 'hot-seat',
      title: 'Hot Seat',
      description: 'Think through the question, then reveal the model answer.',
      group: 'Revision',
      sectionIds: ['hot-seat'],
      aliases: ['revision', 'viva'],
      keywords: ['questions', 'active recall'],
    },
    {
      slug: 'evidence',
      title: 'Evidence',
      description: 'Sources, limitations and outstanding clinical review.',
      group: 'Revision',
      sectionIds: ['evidence-and-references'],
      aliases: ['references'],
      keywords: ['guidelines', 'local policy', 'review'],
    },
  ],
  quickReference: [
    // Clinical snapshot: the authored "At a glance" answers.
    {
      blockId: 'at-a-glance',
      label: 'Presentation',
      page: 'assessment',
      group: 'snapshot',
      itemIndex: 0,
    },
    {
      blockId: 'at-a-glance',
      label: 'Investigations',
      page: 'investigations',
      group: 'snapshot',
      itemIndex: 2,
    },
    {
      blockId: 'at-a-glance',
      label: 'Management',
      page: 'management',
      group: 'snapshot',
      itemIndex: 3,
    },
    {
      blockId: 'at-a-glance',
      label: 'Why it is urgent',
      page: 'assessment',
      group: 'do-not-miss',
      itemIndex: 1,
    },
    {
      blockId: 'deterioration',
      label: 'Do not miss deterioration',
      page: 'assessment',
      group: 'do-not-miss',
    },
    {
      blockId: 'initial-support',
      label: 'Senior help',
      page: 'management',
      group: 'do-not-miss',
      itemIndex: 0,
    },
    {
      blockId: 'appendix-origin',
      label: 'Anatomy & landmarks',
      page: 'anatomy',
      group: 'theatre',
      itemIndex: 1,
    },
    {
      blockId: 'structures-at-risk',
      label: 'Danger areas',
      page: 'anatomy',
      group: 'theatre',
    },
    {
      blockId: 'operation-outline',
      label: 'The operation',
      page: 'appendicectomy',
      group: 'theatre',
    },
    {
      blockId: 'operative-judgement',
      label: 'What can change the plan',
      page: 'appendicectomy',
      group: 'theatre',
    },
    {
      blockId: 'supported-decision',
      label: 'Consent',
      page: 'consent',
      group: 'theatre',
      itemIndex: 2,
    },
    {
      blockId: 'recovery-basics',
      label: 'Postoperative concerns',
      page: 'post-op',
      group: 'after-surgery',
      itemIndex: 1,
    },
    {
      blockId: 'complications-table',
      label: 'Important complications',
      page: 'complications',
      group: 'after-surgery',
    },
  ],
  quickReferenceGroups: [
    { id: 'snapshot', title: 'Clinical snapshot' },
    { id: 'do-not-miss', title: 'Do not miss', tone: 'alert' },
    {
      id: 'theatre',
      title: 'Going to theatre',
      tone: 'feature',
      contextId: 'theatre',
    },
    {
      id: 'after-surgery',
      title: 'After surgery · on the ward',
      contextId: 'ward',
    },
  ],
  contexts: [
    {
      id: 'ward',
      title: 'On the ward',
      description: 'Review, recognise change and plan the next conversation.',
      links: [
        { title: 'Assessment & deterioration', page: 'assessment' },
        { title: 'Postoperative review & safety-netting', page: 'post-op' },
        { title: 'Complications & review gaps', page: 'complications' },
      ],
    },
    {
      id: 'theatre',
      title: 'Going to theatre',
      description:
        'Orientate yourself before the case and discuss with your supervisor.',
      links: [
        { title: 'Anatomy & structures at risk', page: 'anatomy' },
        {
          title: 'Positioning, access & operative sequence',
          page: 'appendicectomy',
        },
        { title: 'Consent discussion', page: 'consent' },
        { title: 'Questions to revise', page: 'hot-seat' },
      ],
    },
  ],
  presentation: [
    {
      blockId: 'symptom-pattern',
      label: 'Presentation pattern',
      itemLabels: [
        'Pain history',
        'Associated features',
        'Atypical presentations',
      ],
      variant: 'cards',
    },
    {
      blockId: 'deterioration',
      label: 'Red flags · escalate',
      variant: 'escalation',
    },
    {
      blockId: 'relevant-history',
      label: 'Diagnostic history',
      variant: 'plain',
    },
    {
      blockId: 'anaesthetic-history',
      label: 'Anaesthetic preparation',
      variant: 'plain',
    },
    { blockId: 'examination', label: 'Examination', variant: 'plain' },
    {
      blockId: 'patient-factors',
      label: 'The individual patient',
      variant: 'plain',
    },
    {
      blockId: 'fluid-assessment',
      label: 'Hydration & circulation',
      variant: 'plain',
    },
    {
      blockId: 'inflammatory-markers',
      label: 'Bloods · inflammatory markers',
      group: 'Bloods & urine',
      variant: 'fact',
    },
    {
      blockId: 'urine-pregnancy',
      label: 'Urine & pregnancy testing',
      group: 'Bloods & urine',
      variant: 'fact',
    },
    {
      blockId: 'renal-tests',
      label: 'Bloods · renal function',
      group: 'Bloods & urine',
      variant: 'fact',
    },
    { blockId: 'sepsis-tests', label: 'Further assessment', variant: 'plain' },
    {
      blockId: 'imaging-choice',
      label: 'Imaging in context',
      variant: 'plain',
    },
    {
      blockId: 'ultrasound',
      label: 'Ultrasound',
      group: 'Imaging modalities',
      variant: 'fact',
    },
    {
      blockId: 'ct-findings',
      label: 'CT',
      group: 'Imaging modalities',
      variant: 'fact',
    },
    {
      blockId: 'mri',
      label: 'MRI',
      group: 'Imaging modalities',
      variant: 'fact',
    },
    {
      blockId: 'diagnostic-synthesis',
      label: 'Bring the findings together',
      variant: 'pathway',
    },
    {
      blockId: 'operative-pathway',
      label: 'Discuss treatment options',
      variant: 'pathway',
    },
    {
      blockId: 'initial-support',
      label: 'Initial support',
      variant: 'pathway',
    },
    { blockId: 'fluid-support', label: 'Assess fluid needs', variant: 'plain' },
    {
      blockId: 'antimicrobial-policy',
      label: 'Follow the applicable policy',
      variant: 'plain',
    },
    {
      blockId: 'nonoperative-discussion',
      label: 'Selected uncomplicated disease',
      variant: 'pathway',
    },
    {
      blockId: 'peritonitis-plan',
      label: 'Peritonitis & deterioration',
      variant: 'escalation',
    },
    {
      blockId: 'abscess-options',
      label: 'Mass / abscess · paediatric context',
      variant: 'pathway',
    },
    {
      blockId: 'appendix-origin',
      label: 'Structures & landmarks',
      itemLabels: ['Origin & relations', 'Finding the base & tip'],
      variant: 'cards',
    },
    {
      blockId: 'mesoappendix',
      label: 'Relational anatomy · mesoappendix',
      variant: 'fact',
    },
    {
      blockId: 'structures-at-risk',
      label: 'Danger areas · why it matters in theatre',
      variant: 'danger',
    },
    {
      blockId: 'operative-sequence',
      label: 'Operative sequence',
      itemLabels: [
        'Position & access',
        'Explore & identify',
        'Mesoappendix & base',
        'Retrieve & assess',
        'Inspect & close',
      ],
      variant: 'steps',
    },
    {
      blockId: 'operative-judgement',
      label: 'Judgement & senior help',
      variant: 'pathway',
    },
    {
      blockId: 'postoperative-review',
      label: 'Review on the ward',
      variant: 'fact',
    },
    {
      blockId: 'discharge-plan',
      label: 'Before discharge',
      variant: 'pathway',
    },
    {
      blockId: 'complications-table',
      label: 'Complication context',
      variant: 'complications',
    },
    {
      blockId: 'supported-decision',
      label: 'A supported decision',
      itemLabels: [
        'Why this procedure?',
        'Reasonable alternatives',
        'Material risks & patient priorities',
        'Questions & understanding',
      ],
      variant: 'consent',
    },
    {
      blockId: 'procedure-specific-discussion',
      label: 'Material risks & what might change',
      variant: 'pathway',
    },
    {
      blockId: 'consent-depth',
      label: 'Patient preferences & understanding',
      variant: 'fact',
    },
  ],
  pathways: [
    {
      id: 'management-overview',
      page: 'management',
      title: 'How the management content fits together',
      caption:
        'Orientation to the sections below — not a treatment algorithm. Follow the linked content, senior advice and local policy.',
      steps: [
        {
          label: 'Initial support, analgesia & senior involvement',
          blockId: 'initial-support',
        },
      ],
      branches: [
        { label: 'Discuss treatment options', blockId: 'operative-pathway' },
        {
          label: 'Generalised peritonitis or deterioration',
          blockId: 'peritonitis-plan',
        },
        { label: 'Mass or abscess', blockId: 'abscess-options' },
      ],
    },
  ],
  related: [
    {
      kind: 'procedure',
      title: 'Laparoscopic appendicectomy',
      page: 'appendicectomy',
    },
    { kind: 'anatomy', title: 'Surgical anatomy', page: 'anatomy' },
    {
      kind: 'complication',
      title: 'Complications after appendicectomy',
      page: 'complications',
    },
  ],
} satisfies TopicExperience;
