import type { Reference } from '@/schemas/reference';

export const references = [
  {
    id: 'nice-gallstones',
    organisation: 'NICE',
    title: 'Gallstone disease: diagnosis and management (CG188)',
    shortTitle: 'NICE CG188',
    year: 2014,
    url: 'https://www.nice.org.uk/guidance/cg188/chapter/Recommendations',
    evidenceType: 'guideline',
    notes:
      'Published 29 October 2014. UK recommendations for diagnosis, gallbladder and bile duct stones, and patient information.',
    accessedAt: '2026-09-29',
  },
  {
    id: 'wses-cholecystitis',
    authors: ['Michele Pisano', 'Niccolò Allievi', 'Kurinchi Gurusamy'],
    organisation: 'World Society of Emergency Surgery',
    publication: 'World Journal of Emergency Surgery',
    title:
      '2020 World Society of Emergency Surgery updated guidelines for the diagnosis and treatment of acute calculus cholecystitis',
    shortTitle: 'WSES 2020 cholecystitis',
    year: 2020,
    url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC7643471/',
    evidenceType: 'guideline',
    notes:
      'First three authors listed. Current WSES edition for acute calculous cholecystitis (open-access full text read). Not UK-specific.',
    accessedAt: '2026-09-29',
  },
  {
    id: 'safe-cholecystectomy',
    authors: ['L. Michael Brunt', 'Daniel J. Deziel', 'Dana A. Telem'],
    publication: 'Annals of Surgery',
    title:
      'Safe Cholecystectomy Multi-society Practice Guideline and State of the Art Consensus Conference on Prevention of Bile Duct Injury During Cholecystectomy',
    shortTitle: 'Multi-society safe cholecystectomy',
    year: 2020,
    url: 'https://www.sages.org/publications/guidelines/safe-cholecystectomy-multi-society-practice-guideline/',
    evidenceType: 'guideline',
    notes:
      'First three authors listed. SAGES, AHPBA, IHPBA, SSAT and EAES; published in Annals of Surgery (doi:10.1097/SLA.0000000000003791). Full text read on the SAGES site. Most recommendations are conditional or expert opinion because of low-certainty evidence; strong recommendations cover biliary imaging for uncertain anatomy or suspected injury, and referral after bile duct injury.',
    accessedAt: '2026-09-29',
  },
  {
    id: 'lapchole-textbook',
    authors: ['Uzair Asad', 'Cecily F. Wang', 'Mark W. Jones'],
    publication: 'StatPearls',
    title: 'Laparoscopic Cholecystectomy',
    shortTitle: 'Textbook laparoscopic cholecystectomy',
    year: 2025,
    url: 'https://www.ncbi.nlm.nih.gov/sites/books/NBK448145/',
    evidenceType: 'textbook',
    notes:
      'StatPearls chapter updated 2 July 2025. Descriptive anatomy and technique; not a guideline. Port positions, devices and closure vary.',
    accessedAt: '2026-09-29',
  },
  {
    id: 'gallbladder-anatomy-textbook',
    authors: ['Mark W. Jones', 'Bradley Boget', 'Tafline C. Arbor'],
    publication: 'StatPearls',
    title: 'Anatomy, Abdomen and Pelvis: Gallbladder',
    shortTitle: 'Textbook gallbladder anatomy',
    year: 2026,
    url: 'https://www.ncbi.nlm.nih.gov/sites/books/NBK459288/',
    evidenceType: 'textbook',
    notes:
      'First three authors listed. StatPearls chapter updated 5 July 2026. Descriptive anatomy, including the original and modern boundaries of the hepatocystic triangle.',
    accessedAt: '2026-09-29',
  },
  {
    id: 'cholecystitis-textbook',
    authors: ['Mark W. Jones', 'Gregory Santos', 'Parth J. Patel'],
    publication: 'StatPearls',
    title: 'Acute Cholecystitis',
    shortTitle: 'Textbook acute cholecystitis',
    year: 2025,
    url: 'https://www.ncbi.nlm.nih.gov/sites/books/NBK459171/',
    evidenceType: 'textbook',
    notes:
      'StatPearls chapter updated 6 July 2025. Descriptive clinical features, differentials and recovery; not a guideline.',
    accessedAt: '2026-09-29',
  },
  {
    id: 'nhs-gallstones',
    organisation: 'NHS',
    title: 'Gallstones',
    shortTitle: 'NHS gallstones',
    year: 2025,
    url: 'https://www.nhs.uk/conditions/gallstones/',
    evidenceType: 'patient-information',
    notes: 'Page reviewed 11 August 2025. Patient-facing overview.',
    accessedAt: '2026-09-29',
  },
  {
    id: 'nhs-cholecystitis',
    organisation: 'NHS',
    title: 'Acute cholecystitis',
    shortTitle: 'NHS cholecystitis',
    year: 2023,
    url: 'https://www.nhs.uk/conditions/acute-cholecystitis/',
    evidenceType: 'patient-information',
    notes:
      'Page reviewed 21 February 2023; its stated review date (February 2026) has passed. Patient-facing overview.',
    accessedAt: '2026-09-29',
  },
  {
    id: 'nhs-gallbladder-removal',
    organisation: 'NHS',
    title: 'Gallbladder removal',
    shortTitle: 'NHS gallbladder removal',
    year: 2025,
    url: 'https://www.nhs.uk/tests-and-treatments/gallbladder-removal/',
    evidenceType: 'patient-information',
    notes:
      'Pages reviewed 3 July 2025 (why, preparation, how it is done, recovery, complications). Patient information, not a protocol.',
    accessedAt: '2026-09-29',
  },
  {
    id: 'rcs-consent',
    organisation: 'Royal College of Surgeons of England',
    title: 'Consent: Supported Decision-Making — A Guide to Good Practice',
    shortTitle: 'RCS consent',
    year: 2016,
    url: 'https://www.rcseng.ac.uk/standards-and-research/standards-and-guidance/good-practice-guides/consent/',
    evidenceType: 'guideline',
    notes:
      'Current RCS consent resource links the 2016 guide; read alongside Good Surgical Practice 2025.',
    accessedAt: '2026-09-29',
  },
  {
    id: 'rcs-gsp',
    organisation: 'Royal College of Surgeons of England',
    title: 'Good Surgical Practice',
    shortTitle: 'RCS practice',
    year: 2025,
    url: 'https://www.rcseng.ac.uk/standards-and-research/good-surgical-practice/',
    evidenceType: 'guideline',
    notes:
      '2025 edition. Professional standards, supervision, records and continuity of care.',
    accessedAt: '2026-09-29',
  },
  {
    id: 'nice-perioperative',
    organisation: 'NICE',
    title: 'Perioperative care in adults (NG180)',
    shortTitle: 'NICE NG180',
    year: 2020,
    url: 'https://www.nice.org.uk/guidance/ng180/chapter/Recommendations',
    evidenceType: 'guideline',
    notes: 'Adult perioperative guidance, not a gallstone guideline.',
    accessedAt: '2026-09-29',
  },
  {
    id: 'nice-vte',
    organisation: 'NICE',
    title:
      'Venous thromboembolism in over 16s: reducing the risk of hospital-acquired deep vein thrombosis or pulmonary embolism (NG89)',
    shortTitle: 'NICE NG89',
    year: 2018,
    url: 'https://www.nice.org.uk/guidance/ng89/chapter/recommendations',
    evidenceType: 'guideline',
    notes: 'Published 2018; updated 2019. VTE and bleeding risk assessment.',
    accessedAt: '2026-09-29',
  },
  {
    id: 'nice-sepsis',
    organisation: 'NICE',
    title:
      'Suspected sepsis in people aged 16 or over: recognition, assessment and early management (NG253)',
    shortTitle: 'NICE NG253',
    year: 2025,
    url: 'https://www.nice.org.uk/guidance/ng253',
    evidenceType: 'guideline',
    notes:
      'Published 19 November 2025. Adult pathway; separate population pathways apply.',
    accessedAt: '2026-09-29',
  },
] satisfies Reference[];
